CREATE TABLE ADA_Apprenants (ApprenantsID INT PRIMARY KEY AUTO_INCREMENT,  apprenants VARCHAR(50), 
                             genre VARCHAR(50));
INSERT INTO ADA_Apprenants (apprenants,genre)
VALUES("Alex","M"),
       ("Amanda.S","F"),
       ("Assetou","F"),
       ("Audrey","F"),
       ("Boris","M"),
       ("Chris","M"),
       ("Cyril","M"),
       ("Clémentine","F"),
       ("Délhia","F"),
       ("Emma","F"),
       ("Faris","M"),
       ("Jacqueline","F"),
       ("Juanita","F"),
       ("Julie B.","F"),
       ("Julie D.","F"),
       ("Karim","M"),
       ("Ladmya","F"),
       ("Mehdi","M"),
       ("Mehmet","M"),
       ("Marielle","F"),
       ("Nicolas","M"),
       ("Quentin","M"),
       ("Woirda","F"),
       ("Zoe","F"),
       ("Melisande","F"),
       ("Romain","M"),
       ("Sandy","F"),
       ("Ulysse","M"),
       ("Sabrina","F");
       
CREATE TABLE ADA_Encadrants (EncadrantsID INT PRIMARY KEY AUTO_INCREMENT,
                             encadrants VARCHAR(50),genre VARCHAR(50));
INSERT INTO ADA_Encadrants (encadrants, genre)
VALUES ("Amendine","F"),
       ("Antoine","M"),
       ("Bruno","F"),
       ("Fred","M"),
       ("Julien","M"),
       ("Kevin","M"),
       ("Laure","F"),
       ("Lucas","M"),
       ("Mickaël","M"),
       ("Romain","M"),
       ("Stéphanie","F"),
       ("Valentin","M"),
       ("Vi","F"),
       ("Céline","F"),
       ("Lucile","F");


CREATE TABLE ADA_membres (id INT PRIMARY KEY AUTO_INCREMENT,ApprenantsID INT,
                          EncadrantsID INT,année YEAR, promo VARCHAR(50),
                          FOREIGN KEY (ApprenantsID)REFERENCES ADA_Apprenants
                          (ApprenantsID),FOREIGN KEY(EncadrantsID) 
                          REFERENCES ADA_Encadrants(EncadrantsID) );
                          
INSERT INTO ADA_membres(année, promo, ApprenantsID)
VALUES("2021", "Clara",2),
      ("2021", "Clara",7),
      ("2021", "Clara",10),
      ("2021", "Clara",17),
      ("2021", "Clara",22),
      ("2021", "Clara",25),
      ("2021", "Clara",26),
      ("2021", "Clara",27),
      ("2021", "Clara",28),
      ("2021", "Clara",29),
      ("2022", "Chimamanda",1),
      ("2022", "Chimamanda",3),
      ("2022", "Chimamanda",4),
      ("2022", "Chimamanda",5),
      ("2022", "Chimamanda",6),
      ("2022", "Chimamanda",8),
      ("2022", "Chimamanda",9),
      ("2022", "Chimamanda",11),
      ("2022", "Chimamanda",13),
      ("2022", "Chimamanda",14),
      ("2022", "Chimamanda",15),
      ("2022", "Chimamanda",16),
      ("2022", "Chimamanda",18),
      ("2022", "Chimamanda",19),
      ("2022", "Chimamanda",20),
      ("2022", "Chimamanda",21),
      ("2022", "Chimamanda",22),
      ("2022", "Chimamanda",23),
      ("2022", "Chimamanda",24);